import { getDb } from "../server/db";
import { evFaults } from "../drizzle/schema";

/**
 * Import Nissan Leaf common faults from research
 */

const nissanLeafFaults = [
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: 2017,
    problemTitle: "Battery Degradation (Passive Air Cooling)",
    description: "Early Leaf models (2011-2017) use passive air cooling causing rapid battery capacity loss, especially in hot climates. The battery chemistry and lack of active thermal management leads to accelerated degradation.",
    symptoms: "Reduced range, loss of battery bars, rapid capacity drop in summer, SOH (State of Health) below 80%, fewer range bars on dashboard",
    resolution: "1) Check battery SOH% using LeafSpy app\n2) Avoid rapid charging in hot weather\n3) Park in shade when possible\n4) 2018+ models have better thermal management\n5) Battery replacement costs £4,000-8,000\n6) Some warranty coverage for severe degradation",
    category: "battery",
    severity: "high",
    frequency: "very_common",
    estimatedCostMin: 4000,
    estimatedCostMax: 8000,
    laborHours: 8.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "12V Battery Failure",
    description: "Small 12V auxiliary battery fails prematurely, leaving vehicle unable to start despite full traction battery. Common issue across all EVs but particularly frequent in Leaf.",
    symptoms: "Car won't power on, warning lights, unable to shift to drive, clicking sounds, complete electrical failure",
    resolution: "1) Replace 12V battery every 3-5 years preventatively\n2) Use quality AGM battery replacement\n3) Check voltage regularly (should be 12.6V+)\n4) Jump start won't help if battery is dead\n5) Costs £100-200 for replacement",
    category: "electrical",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 100,
    estimatedCostMax: 200,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Automatic Emergency Braking (AEB) False Activation",
    description: "AEB system detects phantom objects causing sudden unexpected braking on clear roads. Subject of multiple lawsuits and NHTSA investigations.",
    symptoms: "Random hard braking, system activates with no obstacles, rear-end collision risk, false collision warnings",
    resolution: "1) Subject of multiple lawsuits\n2) Keep sensors and cameras clean\n3) Software updates from Nissan\n4) Can disable AEB system (not recommended)\n5) Report incidents to Nissan and NHTSA",
    category: "safety_systems",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Reduced Range in Cold Weather",
    description: "Dramatic range loss in temperatures below 0°C due to battery chemistry and cabin heating. Can lose 30-50% of range in winter.",
    symptoms: "30-50% range reduction in winter, battery bars drop faster, slower charging, reduced regen braking",
    resolution: "1) Pre-heat cabin while plugged in\n2) Use heated seats instead of cabin heater\n3) Expect 40-60 mile range in winter vs 80-100 in summer\n4) This is normal EV behavior, not a defect\n5) Consider heat pump models (2018+)",
    category: "battery",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2013,
    yearTo: 2015,
    problemTitle: "Occupant Classification System (OCS) Failure",
    description: "Front passenger seat sensor incorrectly detects empty seat, disabling airbag for adult passengers. Subject of multiple recalls.",
    symptoms: "Airbag warning light, passenger airbag off indicator with adult in seat, no warning in some cases",
    resolution: "1) Subject of multiple recalls (2013, 2014)\n2) Software update from Nissan dealer\n3) Sensor mat replacement under warranty\n4) Check airbag status light before every journey\n5) Lawsuit claims fixes don't work",
    category: "safety_systems",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 800,
    laborHours: 2.0,
    sourceType: "recall",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: 2017,
    problemTitle: "Power Inverter Failure",
    description: "Onboard charger/inverter fails causing inability to charge or drive. More common in early models.",
    symptoms: "Won't charge, error codes, loss of power while driving, turtle mode, complete powertrain failure",
    resolution: "1) Diagnostic scan required\n2) Inverter replacement costs £2,000-4,000\n3) Sometimes covered under extended warranty\n4) More common in 2011-2013 models\n5) Requires dealer service",
    category: "motor_drivetrain",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 2000,
    estimatedCostMax: 4000,
    laborHours: 6.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2008,
    yearTo: null,
    problemTitle: "Sunroof Spontaneous Shattering",
    description: "Tempered glass sunroof explodes without impact due to faulty tempering process. Affects Nissan and Infiniti models since 2008.",
    symptoms: "Loud bang, glass raining into cabin, sunroof suddenly shatters while driving or parked",
    resolution: "1) Subject of class-action lawsuit\n2) Replacement covered under warranty if within period\n3) Costs £800-1,200 out of warranty\n4) No preventative measures available\n5) Report to Nissan and NHTSA",
    category: "body_trim",
    severity: "high",
    frequency: "rare",
    estimatedCostMin: 800,
    estimatedCostMax: 1200,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2013,
    yearTo: 2015,
    problemTitle: "Electronic Brake Booster Freezing",
    description: "Electronic brake booster freezes in cold weather making brakes very hard to press. Critical safety issue.",
    symptoms: "Extremely stiff brake pedal, requires excessive force to stop, brake warning light, reduced braking power",
    resolution: "1) Recall issued in 2016\n2) Software update from dealer\n3) Affects cars built 11/19/2012 - 07/31/2015\n4) Free repair under recall\n5) Critical safety issue - get fixed immediately",
    category: "brakes",
    severity: "critical",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 1.0,
    sourceType: "recall",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "CHAdeMO Rapid Charging Issues",
    description: "Incompatibility with some rapid chargers, slow charging speeds, charge port faults. CHAdeMO becoming obsolete.",
    symptoms: "Won't initiate charge at certain stations, charges slower than expected, error messages, communication failures",
    resolution: "1) Try different charging stations\n2) Clean charge port contacts\n3) Battery temperature affects charge speed\n4) CHAdeMO becoming obsolete (CCS is standard now)\n5) Rapid charging degrades battery faster",
    category: "charging",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 500,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Premature Front Tire Wear",
    description: "Heavy battery weight and instant torque cause rapid front tire wear, especially on early models.",
    symptoms: "Front tires worn to 3mm in 15,000-20,000 miles, uneven wear patterns, feathering on edges",
    resolution: "1) Rotate tires every 5,000 miles\n2) Use high-quality tires rated for EV use\n3) Check pressure weekly (EVs are heavy)\n4) Alignment check annually\n5) Expect 20,000-25,000 mile tire life",
    category: "suspension",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 300,
    estimatedCostMax: 600,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Infotainment System Freezing",
    description: "Touchscreen becomes unresponsive, navigation fails, radio/media stops working.",
    symptoms: "Black screen, frozen display, no response to touch, system reboot loops, navigation errors",
    resolution: "1) Hold power button for 10 seconds to reboot\n2) Disconnect 12V battery for 10 minutes\n3) Software updates from dealer\n4) SD card corruption (remove and reformat)\n5) Screen replacement if hardware fault (£800+)",
    category: "infotainment",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 800,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Charging Port Door Issues",
    description: "Charge port door won't open, close, or lock properly.",
    symptoms: "Door stuck closed, won't release, manual release required, door won't latch, frozen in winter",
    resolution: "1) Manual release inside car (see manual)\n2) Lubricate latch mechanism\n3) Check for ice buildup in winter\n4) Latch replacement £150-300\n5) Keep area clean and dry",
    category: "charging",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 150,
    estimatedCostMax: 300,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Brake Actuator Noise",
    description: "Loud grinding/whirring noise from brake actuator during regenerative braking.",
    symptoms: "Mechanical grinding sound when slowing, noise from front of car, vibration through pedal",
    resolution: "1) Usually normal operation sound\n2) Brake fluid flush may help\n3) Actuator replacement if excessive (£1,000+)\n4) More noticeable in cold weather\n5) Does not affect braking performance",
    category: "brakes",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 1000,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "HVAC Weak Airflow",
    description: "Climate control system produces weak airflow, inconsistent temperatures.",
    symptoms: "Barely any air from vents, takes long time to heat/cool, fan noise but no airflow",
    resolution: "1) Replace cabin air filter (every 2 years)\n2) Clean HVAC intake vents\n3) Check for blocked vents or debris\n4) Blower motor replacement if failed (£300-500)\n5) AC recharge if cooling weak",
    category: "hvac",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 50,
    estimatedCostMax: 500,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: 2017,
    problemTitle: "Carwings/NissanConnect Connectivity Issues",
    description: "Remote app features don't work, can't pre-heat/cool car, no remote charging control. 2G/3G network shutdown affected older models.",
    symptoms: "App shows 'not connected', features unavailable, 3G/4G connection lost, remote climate doesn't work",
    resolution: "1) 2G/3G models lost connectivity (network shutdown)\n2) Upgrade to 4G telematics unit (£500-800)\n3) Use timers instead of remote features\n4) Wi-Fi hotspot in car may help\n5) Nissan discontinued support for older models",
    category: "infotainment",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 800,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Suspension Noise and Wear",
    description: "Clunking from suspension, worn bushings, shock absorber issues from heavy battery weight.",
    symptoms: "Knocking over bumps, rattles from front suspension, uneven tire wear, creaking sounds",
    resolution: "1) Inspect bushings and links\n2) Heavy battery accelerates wear\n3) Replace worn components\n4) Costs £200-600 depending on parts\n5) Annual suspension inspection recommended",
    category: "suspension",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 200,
    estimatedCostMax: 600,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Door Handle Malfunctions",
    description: "Exterior door handles stick, don't pop out, or break off.",
    symptoms: "Handle won't extend, stuck flush, requires excessive force, broken mechanism",
    resolution: "1) Lubricate handle mechanism\n2) Check for ice in winter\n3) Handle replacement £150-300 per door\n4) More common in cold climates\n5) Keep handles clean and dry",
    category: "body_trim",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 150,
    estimatedCostMax: 300,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Headlight/Taillight Condensation",
    description: "Moisture buildup inside light housings after rain or temperature changes.",
    symptoms: "Water droplets visible inside lights, fogging, reduced light output",
    resolution: "1) Usually evaporates naturally\n2) Park in sun or warm area\n3) Check for cracked seals\n4) Excessive water requires seal replacement\n5) Does not usually affect function",
    category: "electrical",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 200,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Parking Brake Auto-Release Issues",
    description: "Electronic parking brake doesn't release automatically when shifting to drive.",
    symptoms: "Brake warning light, car won't move, parking brake engaged message",
    resolution: "1) Manually release using switch\n2) Brake actuator calibration at dealer\n3) Software update may fix\n4) Check brake fluid level\n5) Actuator replacement if failed (£800+)",
    category: "brakes",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 800,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Nissan",
    model: "Leaf",
    yearFrom: 2011,
    yearTo: null,
    problemTitle: "Body Rattles and Wind Noise",
    description: "Various rattles from interior trim, wind noise from door seals.",
    symptoms: "Squeaks and rattles over bumps, wind whistle at highway speeds",
    resolution: "1) Identify source of rattle\n2) Tighten trim panels and clips\n3) Replace worn door seals\n4) Sound deadening material can help\n5) Common in older/higher mileage vehicles",
    category: "body_trim",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 50,
    estimatedCostMax: 300,
    laborHours: 2.0,
    sourceType: "research",
  },
];

async function importNissanLeafFaults() {
  console.log("Starting Nissan Leaf faults import...");
  const db = await getDb();
  
  try {
    for (const fault of nissanLeafFaults) {
      await db.insert(evFaults).values(fault);
      console.log(`✓ Imported: ${fault.problemTitle}`);
    }
    
    console.log(`\n✅ Successfully imported ${nissanLeafFaults.length} Nissan Leaf faults`);
  } catch (error) {
    console.error("❌ Error importing faults:", error);
    throw error;
  }
}

// Run the import
importNissanLeafFaults()
  .then(() => {
    console.log("Import complete!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Import failed:", error);
    process.exit(1);
  });
