import { getDb } from "../server/db";
import { evFaults } from "../drizzle/schema";

/**
 * Import BMW i3 common faults from research
 */

const bmwI3Faults = [
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Motor Mount Failure",
    description: "Electric motor mount breaks causing drivetrain vibration and noise, even with gentle driving. Most common i3 problem.",
    symptoms: "Clunking noise on acceleration/deceleration, vibration through floor, rough power delivery, metallic banging",
    resolution: "1) Inspect motor mounts at service intervals\n2) Replacement required when broken\n3) Costs £400-800 for parts and labor\n4) Common even with careful driving\n5) Upgraded aftermarket mounts available",
    category: "motor_drivetrain",
    severity: "high",
    frequency: "very_common",
    estimatedCostMin: 400,
    estimatedCostMax: 800,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "12V Battery Failure",
    description: "Small auxiliary battery fails prematurely leaving car unable to start despite charged main battery. Most common failure point.",
    symptoms: "Car won't power on, warning messages, unable to unlock, dead electronics, clicking sounds",
    resolution: "1) Replace every 4-5 years preventatively\n2) Use BMW genuine or quality AGM replacement\n3) Costs £150-250\n4) Most common i3 failure point\n5) Keep jump starter in car",
    category: "electrical",
    severity: "high",
    frequency: "very_common",
    estimatedCostMin: 150,
    estimatedCostMax: 250,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: 2017,
    problemTitle: "Front Strut Bearing Wear",
    description: "Top strut bearings wear prematurely causing knocking and steering issues. Very common in early models.",
    symptoms: "Clunking over bumps, steering wheel not returning to center, noise when turning, poor handling",
    resolution: "1) Inspect bearings annually\n2) Replace both sides together\n3) Costs £300-600 for pair\n4) More common in early models\n5) Upgraded bearings available",
    category: "suspension",
    severity: "high",
    frequency: "very_common",
    estimatedCostMin: 300,
    estimatedCostMax: 600,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Rusty Brake Discs",
    description: "Brake discs rust quickly due to reliance on regenerative braking. Very common issue.",
    symptoms: "Orange rust on discs, grinding noise when braking, reduced braking performance, pulsation",
    resolution: "1) Use friction brakes regularly (not just regen)\n2) Hard braking once per drive helps\n3) Disc replacement £200-400\n4) Consider coated discs\n5) More common in wet climates",
    category: "brakes",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 200,
    estimatedCostMax: 400,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Charging Port and Cable Issues",
    description: "Charging port fails to lock cable, communication errors, won't charge.",
    symptoms: "Cable won't lock, charging error messages, intermittent charging, port door issues",
    resolution: "1) Clean port contacts regularly\n2) Check cable for damage\n3) Port replacement £400-800\n4) Software update may help\n5) Use multiple charging stations to diagnose",
    category: "charging",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 400,
    estimatedCostMax: 800,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3 REX",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Range Extender (REX) Engine Problems",
    description: "Small petrol engine in REX models has multiple issues. Accounts for half of all i3 problems.",
    symptoms: "Engine warning lights, won't start, rough running, excessive vibration, fuel system errors",
    resolution: "1) Run REX regularly (monthly minimum)\n2) Use premium fuel only\n3) Keep fuel fresh (drain if not used)\n4) Repairs expensive (£1,000+)\n5) BEV models more reliable",
    category: "motor_drivetrain",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 1000,
    estimatedCostMax: 3000,
    laborHours: 4.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Air Conditioning Compressor Failure",
    description: "AC compressor fails catastrophically, shooting metal filings through system. Very expensive repair.",
    symptoms: "No cold air, loud grinding noise, AC error messages, complete system failure",
    resolution: "1) Entire AC system contamination\n2) Requires full system flush and replacement\n3) Costs £2,000-4,000 for complete repair\n4) Not covered under warranty in many cases\n5) Catastrophic and expensive failure",
    category: "hvac",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 2000,
    estimatedCostMax: 4000,
    laborHours: 8.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "High Voltage Battery Degradation",
    description: "Battery capacity loss over time, especially early 60Ah and 94Ah packs.",
    symptoms: "Reduced range, lower SOH%, faster capacity drop in heat/cold, fewer range miles",
    resolution: "1) Check battery SOH% before purchase\n2) 80% SOH at 8 years/100k miles typical\n3) Battery replacement £8,000-12,000\n4) 120Ah packs (2018+) more durable\n5) Avoid rapid charging in extreme temps",
    category: "battery",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 8000,
    estimatedCostMax: 12000,
    laborHours: 10.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Charge Door Mechanism Failure",
    description: "Motorized charge door won't open or close properly.",
    symptoms: "Door stuck closed, won't release, manual release required, motor grinding",
    resolution: "1) Manual release cable inside frunk\n2) Lubricate mechanism\n3) Motor replacement £300-500\n4) Common in cold/wet climates\n5) Keep area clean and dry",
    category: "charging",
    severity: "medium",
    frequency: "common",
    estimatedCostMin: 300,
    estimatedCostMax: 500,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Trim Rattles and Interior Squeaks",
    description: "Carbon fiber body and plastic trim create various rattles and squeaks. Very common complaint.",
    symptoms: "Dashboard rattles, door panel squeaks, headliner noise, center console creaks",
    resolution: "1) Identify source of rattle\n2) Apply felt tape to contact points\n3) Tighten trim clips\n4) Dealer may fix under warranty\n5) Very common complaint",
    category: "body_trim",
    severity: "low",
    frequency: "very_common",
    estimatedCostMin: 0,
    estimatedCostMax: 200,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Wiper Motor and Linkage Issues",
    description: "Wiper motor fails or linkage breaks causing wipers to stop working.",
    symptoms: "Wipers won't move, slow operation, stuck in up position, grinding noise",
    resolution: "1) Check for ice buildup in winter\n2) Linkage replacement £200-400\n3) Motor replacement £300-600\n4) More common in older models\n5) Keep windscreen clear of snow/ice",
    category: "body_trim",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 200,
    estimatedCostMax: 600,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Heated Seat Element Failure",
    description: "Heating elements in seats fail partially or completely.",
    symptoms: "One seat doesn't heat, uneven heating, takes long time to warm, error messages",
    resolution: "1) Check fuse first\n2) Element replacement requires seat removal\n3) Costs £400-800 per seat\n4) Sometimes covered under warranty\n5) More common in high-mileage cars",
    category: "hvac",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 400,
    estimatedCostMax: 800,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "LED Headlight and Taillight Failures",
    description: "Individual LED elements fail in headlight or taillight assemblies.",
    symptoms: "Dark spots in light pattern, warning messages, complete light failure",
    resolution: "1) Cannot replace individual LEDs\n2) Full assembly replacement required\n3) Costs £800-1,500 per headlight\n4) £300-600 per taillight\n5) Check before warranty expires",
    category: "electrical",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 300,
    estimatedCostMax: 1500,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Infotainment System Glitches",
    description: "iDrive system freezes, reboots, loses settings, connectivity issues.",
    symptoms: "Black screen, frozen display, Bluetooth drops, navigation errors, app crashes",
    resolution: "1) Soft reset (hold volume knob 20 seconds)\n2) Software updates from dealer\n3) Hard reset via battery disconnect\n4) Screen replacement if hardware fault (£1,200+)\n5) Fast charging can reset settings",
    category: "infotainment",
    severity: "medium",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 1200,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Drivetrain Malfunction Warnings",
    description: "False drivetrain error messages appear with no actual fault.",
    symptoms: "'Drivetrain malfunction' warning, reduced power mode, car drives normally after restart",
    resolution: "1) Often false alarm from sensors\n2) Restart car to clear\n3) Diagnostic scan required\n4) Software update may fix\n5) Actual drivetrain failures are rare",
    category: "motor_drivetrain",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 200,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Rear-Hinged Door Mechanism Issues",
    description: "Unique rear door hinges and latches develop problems.",
    symptoms: "Door won't open/close properly, alignment issues, latch not catching, squeaking",
    resolution: "1) Lubricate hinges and latches\n2) Adjust door alignment\n3) Latch replacement £200-400\n4) Hinge repair £300-600\n5) Check for wear regularly",
    category: "body_trim",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 200,
    estimatedCostMax: 600,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "TPMS Sensor Errors",
    description: "Tire pressure monitoring system sensors fail or give false warnings.",
    symptoms: "Constant low pressure warnings, sensor not found messages, incorrect readings",
    resolution: "1) Check actual tire pressures first\n2) Reset TPMS via iDrive\n3) Sensor replacement £80-150 each\n4) Battery in sensor lasts 5-7 years\n5) Replace when changing tires",
    category: "electrical",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 80,
    estimatedCostMax: 150,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2013,
    yearTo: null,
    problemTitle: "Parking Brake Actuator Issues",
    description: "Electronic parking brake won't engage or release properly.",
    symptoms: "Brake warning light, won't release, grinding noise, error messages",
    resolution: "1) Manually release via service mode\n2) Actuator calibration at dealer\n3) Actuator replacement £600-1,000\n4) Software update may fix\n5) Keep brake clean and dry",
    category: "brakes",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 600,
    estimatedCostMax: 1000,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "BMW",
    model: "i3",
    yearFrom: 2015,
    yearTo: 2015,
    problemTitle: "Aggressive Regenerative Braking",
    description: "Software issue causes excessive regen braking leading to rear oversteer. Recall issued.",
    symptoms: "Car feels unstable in slippery conditions, rear end slides out, hard to control in rain/snow",
    resolution: "1) Recall issued for affected vehicles\n2) Software update from dealer\n3) Affects Oct-Nov 2015 production\n4) Free repair under recall\n5) Check recall status before purchase",
    category: "brakes",
    severity: "high",
    frequency: "rare",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 1.0,
    sourceType: "recall",
  },
  {
    make: "BMW",
    model: "i3 REX",
    yearFrom: 2013,
    yearTo: 2016,
    problemTitle: "Range Extender Fuel Tank Ventilation Chafing",
    description: "Ventilation line from fuel tank chafes against battery terminal. Fire risk. Recall issued.",
    symptoms: "Fuel vapor smell, potential fire risk, warning lights",
    resolution: "1) Recall issued for affected vehicles\n2) Dealer inspects and replaces line\n3) Additional clips installed\n4) Free repair under recall\n5) Critical safety issue",
    category: "safety_systems",
    severity: "critical",
    frequency: "rare",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 2.0,
    sourceType: "recall",
  },
];

async function importBmwI3Faults() {
  console.log("Starting BMW i3 faults import...");
  const db = await getDb();
  
  try {
    for (const fault of bmwI3Faults) {
      await db.insert(evFaults).values(fault);
      console.log(`✓ Imported: ${fault.problemTitle}`);
    }
    
    console.log(`\n✅ Successfully imported ${bmwI3Faults.length} BMW i3 faults`);
  } catch (error) {
    console.error("❌ Error importing faults:", error);
    throw error;
  }
}

// Run the import
importBmwI3Faults()
  .then(() => {
    console.log("Import complete!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Import failed:", error);
    process.exit(1);
  });
