import { getDb } from "../server/db";
import { evFaults } from "../drizzle/schema";

/**
 * Import Tesla Model 3 common faults from research
 * Based on Tesla_Model3_Top20_Problems_Resolutions.xlsx template
 */

const teslaModel3Faults = [
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null, // Ongoing
    problemTitle: "Touchscreen Failure (MCU1/MCU2)",
    description: "The main touchscreen becomes unresponsive, shows yellow border, or completely fails. More common in early MCU1 units due to eMMC memory wear from excessive logging.",
    symptoms: "Black screen, yellow border warning, unresponsive touch, system reboots, loss of backup camera, no climate control access",
    resolution: "1) Soft reset: hold both scroll wheels for 10 seconds\n2) Hard reset: Power off via Controls > Safety > Power Off\n3) MCU1 upgrade to MCU2 (£1,200-1,500)\n4) eMMC replacement (£500-800)\n5) Tesla may cover under warranty or goodwill",
    category: "infotainment",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 500,
    estimatedCostMax: 1500,
    laborHours: 2.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Phantom Braking (Autopilot/FSD)",
    description: "Vehicle suddenly brakes hard when using Autopilot or Full Self-Driving, despite no obstacles present. Often triggered by shadows, overpasses, or oncoming vehicles.",
    symptoms: "Unexpected hard braking on highway, false collision warnings, autopilot disengages, dangerous for following traffic",
    resolution: "1) Report each incident via voice command 'Bug Report'\n2) Software updates may improve behavior\n3) Disable Autopilot if too frequent\n4) Keep cameras clean\n5) Some improvement with vision-only system vs radar",
    category: "safety_systems",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: 2020,
    problemTitle: "Condensation in Headlights and Taillights",
    description: "Moisture accumulates inside light assemblies after rain or car wash, creating foggy appearance and potential electrical issues.",
    symptoms: "Water droplets visible inside lights, fogging, reduced light output, may trigger warning messages",
    resolution: "1) Park in sun to evaporate naturally\n2) Check for cracked seals\n3) Warranty replacement if excessive\n4) Improved sealing in 2021+ models\n5) Costs £400-800 per assembly out of warranty",
    category: "electrical",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 0,
    estimatedCostMax: 800,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Paint Quality Issues",
    description: "Thin paint chips easily, especially on front bumper, hood, and A-pillars. Clear coat peeling and orange peel texture common.",
    symptoms: "Paint chips from minor road debris, clear coat bubbling, uneven paint texture, premature rust on chips",
    resolution: "1) PPF (Paint Protection Film) on vulnerable areas\n2) Touch-up paint for small chips\n3) Warranty claims if within period\n4) Full respray £2,000-4,000\n5) Tesla improved paint process in 2021+",
    category: "body_trim",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 50,
    estimatedCostMax: 4000,
    laborHours: 8.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Charge Port Door Failure",
    description: "Motorized charge port door won't open, close, or gets stuck. Latch mechanism or motor failure.",
    symptoms: "Door stuck closed, won't release when tapping, manual release required, grinding noise, charge port light issues",
    resolution: "1) Manual release: remove tow eye cover, pull emergency release cable\n2) Soft reset may help\n3) Latch replacement £200-400\n4) Motor replacement £300-500\n5) Keep area clean and lubricated",
    category: "charging",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 200,
    estimatedCostMax: 500,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "12V Battery Failure",
    description: "Small auxiliary battery fails prematurely (typically 2-4 years), leaving car unable to start despite full main battery.",
    symptoms: "Car won't power on, warning messages, unable to unlock, frunk won't open, clicking sounds",
    resolution: "1) Replace every 3-4 years preventatively\n2) Tesla service £150-250\n3) Third-party AGM battery £100-150\n4) Jump start 12V to access frunk\n5) Mobile service available",
    category: "electrical",
    severity: "high",
    frequency: "common",
    estimatedCostMin: 100,
    estimatedCostMax: 250,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: 2021,
    problemTitle: "Chrome Delete Peeling",
    description: "Chrome trim around windows and door handles peels, bubbles, or discolors over time due to poor adhesive or UV exposure.",
    symptoms: "Bubbling chrome wrap, peeling edges, discoloration, exposed black plastic underneath",
    resolution: "1) Warranty replacement if within period\n2) DIY chrome delete with vinyl wrap £50-100\n3) Professional wrap £200-400\n4) 2021+ models have black trim from factory\n5) Remove and replace affected pieces",
    category: "body_trim",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 50,
    estimatedCostMax: 400,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Suspension Noise and Bushing Wear",
    description: "Clunking or creaking from suspension, especially over bumps. Upper control arm bushings wear prematurely.",
    symptoms: "Knocking over bumps, creaking when turning, rattles from front suspension, uneven tire wear",
    resolution: "1) Inspect bushings and control arms\n2) Upper control arm replacement £400-800 per side\n3) Bushing replacement £200-400\n4) Alignment after replacement\n5) More common in Performance models",
    category: "suspension",
    severity: "medium",
    frequency: "common",
    estimatedCostMin: 200,
    estimatedCostMax: 800,
    laborHours: 3.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Range Loss in Cold Weather",
    description: "Significant range reduction in temperatures below 0°C due to battery chemistry, cabin heating, and battery conditioning.",
    symptoms: "30-40% range loss in winter, slower charging, battery preconditioning uses energy, reduced regen braking",
    resolution: "1) Precondition cabin while plugged in\n2) Use seat heaters instead of cabin heat\n3) Enable 'Scheduled Departure' for preconditioning\n4) Heat pump models (2021+) perform better\n5) This is normal EV behavior",
    category: "battery",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Door Handle Mechanism Failure",
    description: "Flush door handles stick, don't present, or break. Microswitches or motor failure common.",
    symptoms: "Handle won't pop out, requires multiple presses, stuck flush, grinding noise, manual release needed",
    resolution: "1) Clean and lubricate mechanism\n2) Microswitch replacement £100-200\n3) Full handle assembly £300-500\n4) Manual release from inside\n5) More common in freezing weather",
    category: "body_trim",
    severity: "medium",
    frequency: "common",
    estimatedCostMin: 100,
    estimatedCostMax: 500,
    laborHours: 1.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Tire Wear (Premature)",
    description: "Heavy vehicle weight and instant torque cause rapid tire wear, especially on rear tires. Performance models worse.",
    symptoms: "Rear tires worn to 3mm in 15,000-20,000 miles, uneven wear, feathering on edges",
    resolution: "1) Rotate tires every 6,250 miles\n2) Use high-performance tires rated for EV\n3) Check pressure weekly (42 PSI cold)\n4) Alignment check annually\n5) Expect 20,000-30,000 mile tire life",
    category: "suspension",
    severity: "medium",
    frequency: "very_common",
    estimatedCostMin: 600,
    estimatedCostMax: 1200,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Rear Drive Unit Failure",
    description: "Rear motor makes whining or grinding noise, loses power, or fails completely. More common in early 2018-2019 models.",
    symptoms: "High-pitched whine at speed, grinding noise, reduced power, 'Powertrain requires service' error, turtle mode",
    resolution: "1) Diagnostic scan required\n2) Drive unit replacement under warranty\n3) Out of warranty: £3,000-5,000\n4) Tesla may offer goodwill coverage\n5) Improved reliability in 2020+ units",
    category: "motor_drivetrain",
    severity: "critical",
    frequency: "occasional",
    estimatedCostMin: 3000,
    estimatedCostMax: 5000,
    laborHours: 6.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Cabin Air Filter Clogging",
    description: "HEPA cabin filter clogs quickly reducing HVAC performance and causing musty smell. Bioweapon Defense Mode affected.",
    symptoms: "Weak airflow, musty odor, reduced heating/cooling, longer defrost time, filter replacement warning",
    resolution: "1) Replace filter every 12-24 months\n2) DIY replacement £30-50 (15 minutes)\n3) Tesla service £80-120\n4) Clean intake vents regularly\n5) Use recirculation mode in dusty areas",
    category: "hvac",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 30,
    estimatedCostMax: 120,
    laborHours: 0.25,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Frunk Latch Failure",
    description: "Front trunk (frunk) won't open, latch stuck, or alignment issues prevent proper closing.",
    symptoms: "Frunk won't open from app or screen, latch stuck, manual release required, misalignment, won't latch closed",
    resolution: "1) Manual release via 12V jump points\n2) Latch adjustment or replacement £150-300\n3) Lubricate latch mechanism\n4) Check for obstruction\n5) Realignment may be needed",
    category: "body_trim",
    severity: "medium",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 300,
    laborHours: 1.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Windshield Wiper Linkage Failure",
    description: "Wiper linkage breaks or comes loose causing wipers to stop working or move erratically.",
    symptoms: "Wipers won't move, stuck in up position, uneven movement, grinding noise, one wiper not moving",
    resolution: "1) Check for ice buildup first\n2) Linkage repair £200-400\n3) Motor replacement if failed £300-500\n4) DIY fix possible with clips\n5) Keep windscreen clear of snow/ice",
    category: "body_trim",
    severity: "high",
    frequency: "occasional",
    estimatedCostMin: 200,
    estimatedCostMax: 500,
    laborHours: 2.0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Bluetooth Connectivity Issues",
    description: "Phone key doesn't work reliably, Bluetooth audio drops, or phone won't connect to car.",
    symptoms: "Car doesn't unlock when approaching, need to use card key, audio cuts out, phone shows disconnected",
    resolution: "1) Delete phone from car and re-pair\n2) Forget car from phone Bluetooth settings\n3) Soft reset both scroll wheels\n4) Update phone and car software\n5) Use key card as backup",
    category: "infotainment",
    severity: "medium",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Trunk Lid Misalignment",
    description: "Rear trunk lid sits uneven, has gaps, or doesn't close flush with body panels.",
    symptoms: "Visible gaps around trunk, uneven panel lines, wind noise at highway speed, water leaks",
    resolution: "1) Adjustment under warranty (free)\n2) Mobile service can adjust on-site\n3) DIY adjustment possible with hex keys\n4) Check rubber seals for damage\n5) Common issue, easy fix",
    category: "body_trim",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 150,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Charging Speed Throttling",
    description: "Supercharging speed slower than expected or throttled due to battery temperature, SOC, or degradation.",
    symptoms: "Charging at 50kW instead of 150kW+, slow charging in hot weather, reduced peak charge rate",
    resolution: "1) Precondition battery before Supercharging\n2) Avoid charging above 80% for faster sessions\n3) Battery temperature affects speed (normal)\n4) Check for software updates\n5) Degradation reduces peak rate over time",
    category: "charging",
    severity: "low",
    frequency: "common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Seat Belt Sensor False Warnings",
    description: "Seat belt warning chimes even when belt is fastened, or passenger seat sensor triggers incorrectly.",
    symptoms: "Constant chiming, 'Fasten seat belt' warning with belt on, passenger airbag light issues",
    resolution: "1) Clean seat belt buckle contacts\n2) Ensure belt fully clicked in\n3) Sensor calibration at service center\n4) Buckle replacement if faulty £100-200\n5) Software update may help",
    category: "safety_systems",
    severity: "low",
    frequency: "occasional",
    estimatedCostMin: 0,
    estimatedCostMax: 200,
    laborHours: 0.5,
    sourceType: "research",
  },
  {
    make: "Tesla",
    model: "Model 3",
    yearFrom: 2017,
    yearTo: null,
    problemTitle: "Regenerative Braking Reduced in Cold",
    description: "Limited regen braking when battery is cold, requiring more use of friction brakes.",
    symptoms: "Dotted line on power meter, reduced regen, need to use brake pedal more, 'Regenerative braking limited' message",
    resolution: "1) Precondition battery before driving\n2) Use 'Scheduled Departure' to warm battery\n3) Regen returns as battery warms up\n4) This is normal battery protection\n5) Heat pump models (2021+) warm faster",
    category: "brakes",
    severity: "low",
    frequency: "very_common",
    estimatedCostMin: 0,
    estimatedCostMax: 0,
    laborHours: 0,
    sourceType: "research",
  },
];

async function importTeslaFaults() {
  console.log("Starting Tesla Model 3 faults import...");
  const db = await getDb();
  
  try {
    for (const fault of teslaModel3Faults) {
      await db.insert(evFaults).values(fault);
      console.log(`✓ Imported: ${fault.problemTitle}`);
    }
    
    console.log(`\n✅ Successfully imported ${teslaModel3Faults.length} Tesla Model 3 faults`);
  } catch (error) {
    console.error("❌ Error importing faults:", error);
    throw error;
  }
}

// Run the import
importTeslaFaults()
  .then(() => {
    console.log("Import complete!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Import failed:", error);
    process.exit(1);
  });
